### ISSUE TITLE
How to ignore files and folders in bashcov in GitLab-CI yaml?

### ISSUE THREAD

**Issue by a-t-0** [infertux/bashcov#66]
Thank you for your work on this project! While trying to run Bashcov on [a basic BATS testing repo](https://github.com/a-t-0/shell_unit_testing_template) in a `.GitLab-CI.yml`:
```yml
image: vergissberlin/alpine-development

stages:
  - build
  - deploy

test:
  stage: build
  image: ruby:slim
  before_script:
    - gem install bashcov
  script:
    # bashcov cannot run as root so here's a magic user
    - useradd -s /bin/bash user
    - su user -c "$(command -v bashcov) test"
  coverage: '/\(\d+\.\d+%\) covered/'
  artifacts:
    untracked: true
```

I receive the error:

> bashcov: warning: encountered an error parsing Bash's output (error was: expected integer for LINENO, got ""). This can occur if your script or its path contains the sequence "010ae148-b419-4384-b227-69b97f25cdb6", or if your script unsets LINENO. Aborting early; coverage report will be incomplete.

So after scanning [the tested repo](https://github.com/a-t-0/shell_unit_testing_template) I noticed the bats installation packages at: `test/libs/bats/*` contain the `$lineno` variable.

[![enter image description here][1]][1]

So I thought I would perhaps be able to circumvent this error by adding the `test/libs/bats/*` dir to the ignored folders when I run `bashcov` with:
```
bashcov bats test
```

However, after inspecting the documentation:
```
bashcov --help
Usage: bashcov [options] [--] <command> [options]
Examples:
    bashcov ./script.sh
    bashcov --skip-uncovered ./script.sh
    bashcov -- ./script.sh --some --flags
    bashcov --skip-uncovered -- ./script.sh --some --flags

Specific options:
    -s, --skip-uncovered             Do not report uncovered files
    -m, --mute                       Do not print script output
        --bash-path PATH             Path to Bash executable
        --root PATH                  Project root directory
        --command-name NAME          Value to use as SimpleCov.command_name

Common options:
    -h, --help                       Show this message
        --version                    Show version
```
I did not find an option to ignore certain folders. Hence, I would like to ask:

*How can I specify ignored folders and files when running `bashcov bats test`?*

  [1]: https://i.stack.imgur.com/6pOFo.png
